# Generated by Django 3.2.25 on 2025-03-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Laundry_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_type', models.CharField(max_length=50)),
                ('machine_status', models.CharField(max_length=50)),
                ('machine_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_use', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('usage_date', models.DateField()),
                ('usage_time', models.TimeField()),
                ('wash_count', models.IntegerField()),
                ('dry_count', models.IntegerField()),
                ('usage_fee', models.IntegerField()),
                ('dry_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dry_usages', to='api.machine')),
                ('wash_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_usages', to='api.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField()),
                ('maintenance_fee', models.IntegerField()),
                ('maintenance_note', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_type', models.CharField(max_length=100)),
                ('expense_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
